### ISSUE TITLE
Unable to run the code

### ISSUE THREAD

**Issue by broy-github** [juryrigcoder/angular-uv-example#1]
Hello,

I am trying to run this angular version of Universal Viewer.
But I am not being able to run the code.
The files **bundle.js** and **UV.js** could not be found in this project.
The folders **uv-assets** and **uv-dist-umd** are not present in this project.

Please help me.

**Comment by juryrigcoder** [comment]
Hi,

Do you get any errors when you run npm i, the uv player should be created in the src folder if the npm install runs correctly.

**Comment by broy-github** [comment]
Ok, I installed the universal viewer in the angular project and found those folders in the  universalviewer folder under ngmodules folder.
Then I copied those folder to the src folder of the angular project.
Now it's working.
Thanks.
